### ISSUE TITLE
详情页无法获取到名称

### ISSUE THREAD

**Issue by jmy126** [pengan1987/famicn#3]
感谢分享，但是详情页无法获取名称？

**Comment by pengan1987** [comment]
请进一步描述你的问题
- 何为详情页？
- 从何处获取？
- 获取“名称”是游戏名？还是厂商名？还是文件名？
- 获取此数据的Use case？

**Comment by jmy126** [comment]
谢谢 回复，http://www.famicn.com/famiclone.html?game=%E9%9B%B7%E7%94%B52%20%5B%E4%B8%89%E5%8D%8F%E8%B5%84%E8%AE%AF%5D
就是这个页面，如何获取到游戏名：雷电2 - 三协资讯
那么这些获取“名称”是游戏名？还是厂商名？还是文件名？
获取此数据的Use case？又该如何获取了？

**Comment by pengan1987** [comment]
从url的query string中可以拿到

**Comment by pengan1987** [comment]
No update, closed
