### ISSUE TITLE
关于中国大亨这个游戏

### ISSUE THREAD

**Issue by livid** [pengan1987/famicn#4]
大部分 NES 模拟器都无法运行这个游戏。

需要一个中国程序员修改过的 Nestopia 的特殊版本 Nestopia Plus! 才能模拟运行。

![image](https://user-images.githubusercontent.com/11427/113990061-edfd7000-9805-11eb-9dab-ff6a55a4cbf3.png)

我在做一个老游戏图鉴项目的过程中遇到过这个问题 :)

https://www.v2ex.com/gamedb/nes/zhongguo-daheng

**Comment by pengan1987** [comment]
Comfirmed this game won't work with MAME, removed from list.
